export const COLLECTIONS = {
  accounts: "accounts",
  abuseReports: "abuseReports",
  apiRateLimits: "apiRateLimits",
  assets: "assets",
  authRateLimits: "authRateLimits",
  databaseMigrations: "databaseMigrations",
  giftRevisions: "giftRevisions",
  gifts: "gifts",
  idempotencyKeys: "idempotencyKeys",
  jobOutbox: "jobOutbox",
  orders: "orders",
  paymentAttempts: "paymentAttempts",
  previewTokens: "previewTokens",
  reactions: "reactions",
  sessions: "sessions",
  templateVersions: "templateVersions",
  templates: "templates",
  technicalSpikes: "technicalSpikes",
  users: "users",
  verifications: "verifications",
  giftPublications: "giftPublications",
  analyticsEvents: "analyticsEvents",
} as const;

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];
